#!/usr/bin/env bash

echo "This setup will help you setup a usb drive to automatically unlock a root luks partition at boot."
echo "This requires a USB disk connected, which will be formatted and erased, and root privileges."  
read -p "Do you wish to continue? [y/N]" luksusbyn
case $luksusbyn in
    [Yy]* ) echo "Searching for USB Disks..."
        for device in /sys/block/*
        do
            if udevadm info --query=property --path=$device | grep -q ^ID_BUS=usb
            then
                usbdevice=$(basename ${device})
                devpath="/dev/$(basename ${device})"
                read -p "USB Disk detected at ${devpath} do you wish to use this disk for LUKS unlock? WARNING: All data on the selected USB will be lost!" usbconfirm 
                case $usbconfirm in 
                    [Yy]* ) echo "USB Confirmed!"
                        break;;
                    * ) echo "Looking for additional USB disks...";;
                esac
            fi
        done
        case $usbconfirm in 
            [Yy]* ) echo "Unmounting any mounted partitions from USB..."
                umount ${devpath}?*
                echo "Disk partitions unmounted!"
                read -p "This is your last warning! All data on the disk ${devpath} will be erased if you continue! Do you wish to continue? [y/N]" formatyn
                case $formatyn in
                    [Yy]* ) echo "Formatting disk..."
                    echo "This is where the disk would be formatted."
                    echo "This is where the keyfile would be generated"
                    echo "This is where the keyfile would be added to your luks disk"
                    echo "This is where the keyfile would be copied to your usb drive"
                    echo "This is where the keyfile would be added to crypttab"
                    echo "This is where you would rebuild your boot image with dracut -f"
                    echo "USB key successfully created! Your computer's Luks partition should unlock automatically at boot so long as the USB key is connected."
                    echo "If the USB key is not detected, the system will wait for a standard password input."
                    echo "Luks USB key unlock setup is complete!";;
                    * ) echo "Format canceled! You can rerun this script later if you wish to continue.";;
                esac;;
            * ) echo "No USB key selected. Exiting without making any changes.";;
        esac
    * ) echo "No changes to luks disk unlock will be made.";;
esac
